version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
      - "3035:3035"
      - "9000:9000"
      - "4000:4000"